// data.js — pure game data constants for Tornaris

const CHARACTERS = [
  {
    id: 'celeste',
    name: 'Celeste',
    class: 'Druida',
    emoji: '🌿',
    passive: 'Empieza con 1 de maná adicional permanente.',
    startItems: '2x Poción de Maná',
    maxMana: 5,
  },
  {
    id: 'skull',
    name: 'Skull',
    class: 'Nigromante',
    emoji: '💀',
    passive: 'Al entrar a cualquier combate puede tomar 1 equipamiento aleatorio de la baraja de descarte (Si existe). Debe devolverlo al finalizar el combate.',
    startItems: '2x Portal de Bolsillo',
    maxMana: 4,
  },
  {
    id: 'remi',
    name: 'Remi',
    class: 'Hombre Topo',
    emoji: '🦔',
    passive: 'Todas las compras en la tienda valen 2 monedas menos. Al sacar un 6 en cualquier lanzamiento de dado gana 3 de oro.',
    startItems: '2x Cuervo Mensajero',
    maxMana: 4,
  },
  {
    id: 'baltazar',
    name: 'Baltazar',
    class: 'Mago',
    emoji: '🔮',
    passive: 'Una vez por combate puede repetir uno de sus dados.',
    startItems: '2x Cristal Vidente',
    maxMana: 4,
  },
  {
    id: 'braulia',
    name: 'Braulia',
    class: 'Escudera',
    emoji: '🛡️',
    passive: 'Tiene 8 espacios de equipamiento en vez de 6.',
    startItems: '2x Invocación de Familiar',
    maxMana: 4,
  },
  {
    id: 'nyra',
    name: 'Nyra',
    class: 'Cazadora',
    emoji: '🏹',
    passive: 'Al ganar un combate contra un jugador le roba 7 de oro (Adicional si hay otro tipo de recompensa).',
    startItems: '2x Guante del Duelo',
    maxMana: 4,
  },
];

// Tier: 'duende'(1-5), 'ogro'(6-10), 'golem'(11-15), 'dragon'(16-20)
const MONSTERS = [
  {
    id: 1,
    name: 'Grumo',
    tier: 'duende',
    image: 'assets/img/monster_1.png',
    hp: '3x',
    minPlayers: 1,
    reward: '5 de oro',
    ability: 'El primer combatiente lanza un dado, se suma esa cantidad a la vida del monstruo.',
    penalty: '2 de oro',
  },
  {
    id: 2,
    name: 'Diablillo',
    tier: 'duende',
    image: 'assets/img/monster_2.png',
    hp: '4x',
    minPlayers: 1,
    reward: '1 equipamiento aleatorio',
    ability: 'Todos los combatientes repiten su dado más alto una vez.',
    penalty: '3 de oro',
  },
  {
    id: 3,
    name: 'Mímico',
    tier: 'duende',
    image: 'assets/img/monster_3.png',
    hp: '4x',
    minPlayers: 1,
    reward: '10 de oro',
    ability: 'El monstruo gana el combate automáticamente si van TODOS los jugadores.',
    penalty: '4 de oro',
  },
  {
    id: 4,
    name: 'Sirena',
    tier: 'duende',
    image: 'assets/img/monster_4.png',
    hp: '5x',
    minPlayers: 1,
    reward: '1 equipamiento aleatorio',
    ability: 'Si la Sirena es derrotada, todos los jugadores que no participaron pierden 2 de oro.',
    penalty: '3 de oro',
  },
  {
    id: 5,
    name: 'Esqueleto Guerrero',
    tier: 'duende',
    image: 'assets/img/monster_5.png',
    hp: '5x',
    minPlayers: 1,
    reward: '1 equipamiento aleatorio',
    ability: 'Si el grupo falla en derrotarlo, el monstruo reaparece el siguiente turno con la misma vida.',
    penalty: '2 de oro',
  },
  {
    id: 6,
    name: 'Troll',
    tier: 'ogro',
    image: 'assets/img/monster_6.png',
    hp: '8x',
    minPlayers: 1,
    reward: '1 equipamiento aleatorio + 5 de oro',
    ability: 'El combatiente con el dado más bajo no recibe recompensa.',
    penalty: '4 de oro',
  },
  {
    id: 7,
    name: 'Sombra Acechante',
    tier: 'ogro',
    image: 'assets/img/monster_7.png',
    hp: '5x',
    minPlayers: 1,
    reward: '1 equipamiento aleatorio + 3 de oro',
    ability: 'El jugador con el primer turno en el combate juega por el monstruo: lanza 2 dados por cada otro combatiente y suma ese total a la vida del monstruo. Si el monstruo gana, ese jugador recibe la recompensa. Si pierde, sufre la penitencia.',
    penalty: '4 de oro + descarta 1 equipamiento',
  },
  {
    id: 8,
    name: 'Bruja',
    tier: 'ogro',
    image: 'assets/img/monster_8.png',
    hp: '8x',
    minPlayers: 1,
    reward: '1 equipamiento aleatorio',
    ability: 'Los jugadores no pueden usar equipamientos, pero cada combatiente lanza 3 dados en vez de 2.',
    penalty: '4 de oro',
  },
  {
    id: 9,
    name: 'Hongo Alien',
    tier: 'ogro',
    image: 'assets/img/monster_9.png',
    hp: '6x',
    minPlayers: 1,
    reward: '1 equipamiento aleatorio',
    ability: 'Al ser derrotado, cada combatiente lanza un dado y gana ese resultado en oro.',
    penalty: 'Cada combatiente lanza un dado y pierde ese resultado en oro.',
  },
  {
    id: 10,
    name: 'Horda Zombie',
    tier: 'ogro',
    image: 'assets/img/monster_10.png',
    hp: '4x',
    minPlayers: 2,
    reward: '2 equipamientos aleatorios + 8 de oro',
    ability: 'El monstruo gana +3 de vida por cada jugador que no participe en el combate.',
    penalty: '5 de oro',
  },
  {
    id: 11,
    name: 'Basilisco de Fuego',
    tier: 'golem',
    image: 'assets/img/monster_11.png',
    hp: '7x',
    minPlayers: 2,
    reward: '2 equipamientos aleatorios + 8 de oro',
    ability: 'El combatiente con el total más bajo es forzado a descansar la noche siguiente.',
    penalty: '4 de oro',
  },
  {
    id: 12,
    name: 'Cocatriz',
    tier: 'golem',
    image: 'assets/img/monster_12.png',
    hp: '7x',
    minPlayers: 2,
    reward: '2 equipamientos aleatorios + 10 de oro',
    ability: 'Cualquier combatiente con resultado total de 8 o menos no recibe recompensa.',
    penalty: '5 de oro',
  },
  {
    id: 13,
    name: 'Musgo Viviente',
    tier: 'golem',
    image: 'assets/img/monster_13.png',
    hp: '7x',
    minPlayers: 2,
    reward: '2 equipamientos aleatorios + 10 de oro',
    ability: 'Después del combate, el mejor lanzador recibe 2 monedas de cada combatiente.',
    penalty: '6 de oro',
  },
  {
    id: 14,
    name: 'Dullahan',
    tier: 'golem',
    image: 'assets/img/monster_14.png',
    hp: '8x',
    minPlayers: 2,
    reward: '2 equipamientos aleatorios + 12 de oro',
    ability: 'Si el monstruo es derrotado, el jugador con más oro pierde 10 monedas.',
    penalty: '6 de oro',
  },
  {
    id: 15,
    name: 'Rey Nigromante',
    tier: 'golem',
    image: 'assets/img/monster_15.png',
    hp: '8x',
    minPlayers: 2,
    reward: '2 equipamientos aleatorios + 12 de oro',
    ability: 'Al ser derrotado, deben hacerlo de nuevo con vida de 5 x combatiente y sin equipamientos.',
    penalty: 'Descarta 1 equipamiento',
  },
  {
    id: 16,
    name: 'Polilla Gigante',
    tier: 'dragon',
    image: 'assets/img/monster_16.png',
    hp: null,
    minPlayers: 2,
    reward: '2 equipamientos aleatorios + 14 de oro',
    ability: 'Cada combatiente elige en secreto: adelante ayuda a la Polilla, hacia sí mismo ayuda al grupo. Cada bando suma sus dados y el mayor total gana. Si solo hay 1 jugador, toma una carta de evento en vez de pelear. En caso de empate, el monstruo gana.',
    penalty: '10 de oro',
  },
  {
    id: 17,
    name: 'Gigante de Hielo',
    tier: 'dragon',
    image: 'assets/img/monster_17.png',
    hp: '7x',
    minPlayers: 3,
    reward: '3 equipamientos aleatorios + 15 de oro',
    ability: 'En vez de lanzar los dados normalmente, todos los combatientes empiezan con 1 en ambos dados y solo pueden modificarlos con equipamientos.',
    penalty: '6 de oro y el peor lanzador descarta 1 equipamiento',
  },
  {
    id: 18,
    name: 'Balrog "Señor Abisal"',
    tier: 'dragon',
    image: 'assets/img/monster_18.png',
    hp: '8x',
    minPlayers: 3,
    reward: '1 maná adicional',
    ability: 'Para participar en este combate, debes hacer una ofrenda. Lanza un dado: 1-3 sacrificas 1 equipamiento a elección, 4-6 sacrificas 15 de oro. Si no puedes pagar, no puedes participar.',
    penalty: '10 de oro y el peor lanzador descarta 1 equipamiento',
  },
  {
    id: 19,
    name: 'Dragón Terrestre',
    tier: 'dragon',
    image: 'assets/img/monster_19.png',
    hp: 15,
    minPlayers: 3,
    reward: '1 maná adicional + 10 de oro',
    ability: 'Cada jugador debe vencerlo individualmente.',
    penalty: '10 de oro y el peor lanzador pierde 1 maná adicional permanentemente',
  },
  {
    id: 20,
    name: 'Rey de los Cielos',
    tier: 'dragon',
    image: 'assets/img/monster_20.png',
    hp: '10x',
    minPlayers: 3,
    reward: '1. Maná adicional  2. 3 equipamientos aleatorios  3. 30 de oro (en orden de apuesta)',
    ability: 'Cada jugador apuesta oro en orden de turno (el oro apostado siempre se pierde). Si ganan, los premios se reparten de mayor a menor apuesta. En empate, los empatados comparten el mismo premio.',
    penalty: 'Los jugadores que no participen y el jugador con la menor apuesta pierden 2 equipamientos a elección.',
  },
];

const TIER_ORDER = ['duende', 'ogro', 'golem', 'dragon'];

const DAY_EVENTS = [
  { id: 1,  name: 'Día Normal',          effect: 'Un día ordinario en el reino.',                                                                      count: 8 },
  { id: 2,  name: 'Feria del Gremio',    effect: 'Hoy se revelan 2 cartas por jugador en la tienda en vez de 1.',                                      count: 2 },
  { id: 3,  name: 'Día de Tregua',       effect: 'Nadie puede iniciar duelos hoy.',                                                                     count: 2 },
  { id: 4,  name: 'Monstruo Legendario', effect: 'El monstruo de la mazmorra hoy tiene el doble de vida pero otorga el doble de recompensa.',           count: 2 },
  { id: 5,  name: 'Día de Suerte',       effect: 'Todos los jugadores pueden elegir 1 objeto de su preferencia al inicio del día.',                     count: 2 },
  { id: 6,  name: 'Mazmorra Cerrada',    effect: 'Nadie puede ir a la mazmorra hoy. La carta de monstruo se descarta.',                                 count: 2 },
  { id: 7,  name: 'Doble Evento',        effect: 'Los jugadores en casilla de evento roban 2 cartas hoy.',                                              count: 3 },
  { id: 8,  name: 'Mercado Negro',       effect: 'Los equipamientos en tienda cuestan la mitad hoy.',                                                   count: 2 },
  { id: 9,  name: 'Día de Caza',         effect: 'Los monstruos de mazmorra otorgan el doble de recompensa hoy.',                                       count: 2 },
  { id: 10, name: 'Torre en Disputa',    effect: 'Ningún jugador puede cobrar ingresos de sus torres hoy.',                                             count: 1 },
  { id: 11, name: 'Día Caótico',         effect: 'El orden de turno se invierte hoy.',                                                                  count: 1 },
  { id: 12, name: 'Día Transparente',    effect: 'Hoy las flechas son visibles. Los jugadores eligen su casilla en orden de turno.',                    count: 1 },
  { id: 13, name: 'Recuperación General',effect: 'Todos los jugadores recuperan todo su maná al inicio del día.',                                       count: 2 },
];

const NIGHT_EVENTS = [
  { id: 1,  name: 'Noche Normal',           effect: 'La oscuridad llega sin novedades esta noche.',                                                    count: 4 },
  { id: 2,  name: 'Ingresos Extra',         effect: 'Los jugadores que trabajen esta noche ganan el doble de oro.',                                    count: 3 },
  { id: 3,  name: 'Competencia en el Ring', effect: 'Pueden realizarse 2 peleas en el ring esta noche en vez de 1.',                                   count: 2 },
  { id: 4,  name: 'Descanso Obligatorio',   effect: 'Todos los jugadores recuperan todo su maná.',                                                     count: 2 },
  { id: 5,  name: 'Mercado Nocturno',       effect: 'La tienda está disponible esta noche, remplazando la casilla de "Trabajo".',                      count: 1 },
  { id: 6,  name: 'Noche Tranquila',        effect: 'El ring está cerrado esta noche. Nadie puede iniciar duelos.',                                    count: 1 },
  { id: 7,  name: 'Noche de Caos',          effect: 'El orden de turno se invierte esta noche.',                                                       count: 1 },
  { id: 8,  name: 'Bonanza',               effect: 'Todos los jugadores reciben 5 de oro adicional al inicio de la noche.',                            count: 2 },
  { id: 9,  name: 'Remate Nocturno',        effect: 'Esta noche todos los jugadores pueden vender equipamientos por su precio completo.',               count: 2 },
  { id: 10, name: 'Noche Mágica',           effect: 'Todos los jugadores recuperan todo su maná al inicio de la noche.',                               count: 1 },
  { id: 11, name: 'El Oráculo',             effect: 'Se revela la próxima carta de monstruo de la baraja de mazmorras.',                               count: 1 },
];

const EQUIPMENT = [
  { id: 1,  name: 'Escudo Pesado',       text: 'Ataque +X (X = valor de un dado de otro jugador en juego que elijas).',                                                    count: 3, price: 10, mana: 3 },
  { id: 2,  name: 'Ruleta Maligna',      text: 'Por cada dado impar en juego: Ataque +3. Por cada par: Ataque +1.',                                                        count: 2, price: 10, mana: 2 },
  { id: 3,  name: 'Comodín',             text: 'Lanza un dado adicional.',                                                                                                 count: 3, price: 10, mana: 3 },
  { id: 4,  name: 'Doble Espada',        text: 'Ataque +X (X = valor de uno de tus dados).',                                                                               count: 1, price: 12, mana: 3 },
  { id: 5,  name: 'Sello Maligno',       text: 'Obliga a cualquier jugador a repetir su tirada.',                                                                          count: 2, price: 12, mana: 2 },
  { id: 6,  name: 'Corona de Arturo',    text: 'Si en este momento el rival tiene mayor total, tu total pasa a ser el suyo +1. Mazmorra: Ataque +3.',                      count: 1, price: 14, mana: 2 },
  { id: 7,  name: 'Escudo Mágico',       text: 'Anula la próxima carta del rival en este combate. Mazmorra: Ataque +1.',                                                   count: 2, price: 6,  mana: 2 },
  { id: 8,  name: 'Ruleta',              text: 'Ataque +2 por cada dado impar tuyo.',                                                                                      count: 2, price: 6,  mana: 2 },
  { id: 9,  name: 'Amplificador',        text: 'Ataque +6 si tienes al menos dos dados iguales.',                                                                          count: 2, price: 6,  mana: 2 },
  { id: 10, name: 'Rayo Mortal',         text: 'Ataque +6 si tienes un 6.',                                                                                               count: 2, price: 6,  mana: 2 },
  { id: 11, name: 'Doble Filo',          text: 'Intercambia uno de tus dados por otro dado en juego.',                                                                     count: 2, price: 6,  mana: 3 },
  { id: 12, name: 'Hacha de Batalla',    text: 'Elige uno de tus dados y cámbialo al valor del otro.',                                                                     count: 2, price: 8,  mana: 2 },
  { id: 13, name: 'Resorte',             text: 'Repite hasta 2 de tus dados.',                                                                                             count: 3, price: 8,  mana: 1 },
  { id: 14, name: 'Afilador',            text: 'Sube +3 a uno de tus dados (máximo 6).',                                                                                   count: 2, price: 8,  mana: 2 },
  { id: 15, name: 'Pergamino Oscuro',    text: 'Roba un equipamiento al azar del mazo y úsalo ignorando coste de maná. Devuélvelo al fondo al final del combate.',         count: 2, price: 8,  mana: 2 },
  { id: 16, name: 'Varita Mágica',       text: 'Ataque +3 si el rival tiene más maná que tú. Mazmorra: Ataque +3.',                                                        count: 2, price: 12, mana: 1 },
  { id: 17, name: 'Espejo de Bolsillo',  text: 'Copia el efecto de un equipamiento de cualquier jugador en juego.',                                                        count: 2, price: 10, mana: 2 },
  { id: 18, name: 'Botas Ligeras',       text: 'Ataque +1 por cada dado de otro jugador en juego. Mazmorra: Ataque +1.',                                                   count: 2, price: 8,  mana: 1 },
  { id: 19, name: 'Daga Hechizada',      text: 'Ataque +1 por cada dado impar en la mesa. Mazmorra: Ataque +3.',                                                           count: 2, price: 12, mana: 1 },
  { id: 20, name: 'Cota de Piedra',      text: 'Ataque +5.',                                                                                                               count: 2, price: 10, mana: 3 },
  { id: 21, name: 'Reloj de Arena',      text: 'Repite todos los dados de todos los jugadores en juego.',                                                                   count: 2, price: 8,  mana: 2 },
  { id: 22, name: 'Mazo',                text: 'Ataque +2.',                                                                                                               count: 3, price: 4,  mana: 1 },
  { id: 23, name: 'Normalizador',        text: 'Elige un dado tuyo y uno de otro jugador: cámbialos a 3.',                                                                  count: 3, price: 4,  mana: 2 },
  { id: 24, name: 'Caja Sorpresa',       text: 'Repite 1 dado hasta 2 veces.',                                                                                             count: 3, price: 4,  mana: 1 },
  { id: 25, name: 'Escudo Ligero',       text: 'Ataque +2.',                                                                                                               count: 3, price: 4,  mana: 1 },
  { id: 26, name: 'Daga',                text: 'Ataque +1 por cada equipamiento que hayas usado antes en este combate.',                                                    count: 3, price: 4,  mana: 1 },
  { id: 27, name: 'Capa del Rey Demonio',text: 'Toma un equipamiento de la mano del rival y úsalo ignorando coste. Devuélvelo al final. Mazmorra: Ataque +3.',             count: 1, price: 14, mana: 3 },
  { id: 28, name: 'Escudo de Cuero',     text: 'Ataque +1 por cada equipamiento que el rival haya usado en este combate. Mazmorra: Ataque +1.',                            count: 3, price: 4,  mana: 1 },
  { id: 29, name: 'Caña de Pescar',      text: 'Anula 1 equipamiento del rival. Mazmorra: Ataque +1.',                                                                     count: 2, price: 6,  mana: 3 },
  { id: 30, name: 'Escudito',            text: 'Ataque +1.',                                                                                                               count: 3, price: 4,  mana: 0 },
  { id: 31, name: 'Plaga',               text: 'Ataque propio -2. Al final del combate pasa al rival. No puede descartarse, venderse ni usarse en mazmorras.',              count: 1, price: 0,  mana: 0 },
  { id: 32, name: 'Armadura de Arturo',  text: 'Anula todos los equipamientos en juego. Un jugador elegido repite sus dados. Mazmorra: Ataque +3.',                        count: 1, price: 14, mana: 2 },
  { id: 33, name: 'Espadita',            text: 'Ataque +1.',                                                                                                               count: 3, price: 4,  mana: 0 },
  { id: 34, name: 'Espada de Sigurd',    text: 'Ataque +1 por cada equipamiento usado antes en este combate.',                                                             count: 1, price: 14, mana: 1 },
  { id: 35, name: 'Trampa para Osos',    text: 'Ataque +3 si hubo un cambio de dados en este combate.',                                                                    count: 3, price: 4,  mana: 1 },
  { id: 36, name: 'Daga Envenenada',     text: 'Ataque +1 por cada equipamiento que el rival juegue después de esta carta. Mazmorra: Ataque +3.',                          count: 2, price: 12, mana: 1 },
  { id: 37, name: 'Martillo Ligero',     text: 'Ataque +3 si todos tus dados son pares.',                                                                                  count: 2, price: 1,  mana: 1 },
  { id: 38, name: 'Escama Antigua',      text: 'Ataque +3 si el rival tiene algún 6. Mazmorra: Ataque +1 por cada 10 de vida base del monstruo.',                          count: 2, price: 1,  mana: 1 },
  { id: 39, name: 'Dados Gemelos',       text: 'Ataque +4 si tus dados muestran el mismo valor.',                                                                          count: 2, price: 1,  mana: 1 },
  { id: 40, name: 'Ojo del Dragón',      text: 'Mira la mano del rival. Elige 1 carta: no puede usarla este combate. Mazmorra: Ataque +2.',                                count: 1, price: 6,  mana: 2 },
  { id: 41, name: 'Candado Rúnico',      text: 'Elige al azar 1 carta de la mano del rival: no puede usarla este combate. Mazmorra: Ataque +1.',                           count: 2, price: 1,  mana: 1 },
  { id: 42, name: 'Armadura Rota',       text: 'Ataque +4, pero no puedes haber usado ni usar cartas en este combate después de esta.',                                    count: 2, price: 1,  mana: 1 },
];
